meta_title: "Pronostik - Bet on the future, outsmart experts and stay ahead of the curve."
meta_description: "Pronostik let you bet on various questions, and have access to interesting statistics pertaining to current events. Together, we can paint a reliable of the future."
meta_image: "logoProno.png"  # A picture in your app / assets / images /
twitter_account: "@nomdevotrecompte"  # essential for Twitter Cards
